[package]
name = "dota2api"
version = "0.1.0"
authors = ["Dan Ambrisco <dambrisco@gmail.com>"]

[dependencies]
hyper = "0.10"
hyper-native-tls = "0.2.1"
json = "0.11.5"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
